Repository BDD-CLUB/01-doo-re-back, pull requests merged in 2024-06, with the labels that each got.

#131 Feature/#125 member team의 권한 로직을 수정한다
  src/main/java/doore/member/api/MemberTeamController.java
  src/main/java/doore/member/application/MemberTeamQueryService.java
  src/main/java/doore/member/application/dto/response/TeamMemberResponse.java
  src/main/java/doore/member/domain/repository/TeamRoleRepository.java
  src/test/java/doore/helper/ApiTestHelper.java
  src/test/java/doore/member/api/MemberTeamControllerTest.java
  src/test/java/doore/member/application/MemberTeamQueryServiceTest.java
  src/test/java/doore/restdocs/docs/MemberTeamApiDocsTest.java
Labels: 🌱 기능 구현

#134 Feature/#127 팀 상세 조회 기능 구현
  src/docs/asciidoc/team.adoc
  src/main/java/doore/attendance/domain/repository/AttendanceRepository.java
  src/main/java/doore/team/api/TeamController.java
  src/main/java/doore/team/application/TeamQueryService.java
  src/main/java/doore/team/application/dto/response/TeamResponse.java
  src/test/java/doore/restdocs/docs/TeamApiDocsTest.java
  src/test/java/doore/team/application/TeamQueryServiceTest.java
Labels: 🌱 기능 구현

#145 [REFACTOR] participantCurriculumItem 목록 조회 테스트 리팩토링
  src/test/java/doore/study/CurriculumItemFixture.java
  src/test/java/doore/study/ParticipantCurriculumItemFixture.java
  src/test/java/doore/study/ParticipantFixture.java
  src/test/java/doore/study/domain/ParticipantCurriculumItemRepositoryTest.java
Labels: 🛠️ 리팩터링

#152 Feature/#151 나의 스터디 조회 response 변경
  src/main/java/doore/member/domain/repository/ParticipantRepository.java
  src/main/java/doore/study/api/StudyController.java
  src/main/java/doore/study/application/StudyQueryService.java
  src/test/java/doore/restdocs/docs/StudyApiDocsTest.java
  src/test/java/doore/study/application/StudyQueryServiceTest.java
Labels: 🌱 기능 구현

#153 Feature/#137 조회 테스트 수정
  src/test/java/doore/document/application/DocumentCommandServiceTest.java
  src/test/java/doore/restdocs/docs/MemberTeamApiDocsTest.java
  src/test/java/doore/restdocs/docs/TeamApiDocsTest.java
  src/test/java/doore/team/application/TeamCommandServiceTest.java
Labels: 🐛 버그

#156 Feature/#155 스터디 조회 정보에 스터디 진행률을 포함한다
  src/main/java/doore/study/application/StudyQueryService.java
  src/main/java/doore/study/application/dto/response/StudyResponse.java
  src/main/java/doore/study/domain/repository/CurriculumItemRepository.java
  src/main/java/doore/study/domain/repository/ParticipantCurriculumItemRepository.java
  src/test/java/doore/restdocs/docs/StudyApiDocsTest.java
  src/test/java/doore/study/application/StudyQueryServiceTest.java
Labels: 🌱 기능 구현

#168 Feature/#164 팀의 garden 조회 로직을 수정한다
  src/docs/asciidoc/garden.adoc
  src/main/java/doore/garden/api/GardenController.java
  src/main/java/doore/garden/application/GardenQueryService.java
  src/main/java/doore/garden/application/dto/response/DayGardenResponse.java
  src/main/java/doore/garden/domain/repository/GardenRepository.java
  src/main/java/doore/team/application/TeamQueryService.java
  src/test/java/doore/garden/application/GardenQueryServiceTest.java
  src/test/java/doore/restdocs/docs/GardenApiDocsTest.java
  src/test/java/doore/restdocs/docs/TeamApiDocsTest.java
Labels: 🌱 기능 구현

#169 Feature/#166 get my teams and studies에 개인정보 추가
  src/docs/asciidoc/member.adoc
  src/main/java/doore/member/api/MemberController.java
  src/main/java/doore/member/application/MemberQueryService.java
  src/main/java/doore/member/application/dto/response/MemberAndMyTeamsAndStudiesResponse.java
  src/main/java/doore/team/api/TeamController.java
  src/main/java/doore/team/application/TeamQueryService.java
  src/main/java/doore/team/application/dto/response/MyTeamsAndStudiesResponse.java
  src/test/java/doore/restdocs/RestDocsTest.java
  src/test/java/doore/restdocs/docs/MemberApiDocsTest.java
  src/test/java/doore/restdocs/docs/TeamApiDocsTest.java
Labels: 🌱 기능 구현

#176 Feature/#171 팀 스터디 상세조회에 leader 정보를 추가한다
  src/main/java/doore/member/domain/repository/StudyRoleRepository.java
  src/main/java/doore/member/domain/repository/TeamRoleRepository.java
  src/main/java/doore/study/api/StudyController.java
  src/main/java/doore/study/application/StudyQueryService.java
  src/main/java/doore/study/application/dto/response/StudyReferenceResponse.java
  src/main/java/doore/study/application/dto/response/StudyResponse.java
  src/main/java/doore/team/application/TeamQueryService.java
  src/main/java/doore/team/application/dto/response/TeamResponse.java
  src/test/java/doore/restdocs/docs/StudyApiDocsTest.java
  src/test/java/doore/restdocs/docs/TeamApiDocsTest.java
  src/test/java/doore/study/application/StudyQueryServiceTest.java
  src/test/java/doore/team/application/TeamQueryServiceTest.java
Labels: 🌱 기능 구현
