Repository BDD-CLUB/01-doo-re-back, pull requests merged in 2024-05, with the labels that each got.

#106 Feature/#94 내가 속한 팀 스터디 목록 조회
  src/docs/asciidoc/study.adoc
  src/docs/asciidoc/team.adoc
  src/main/java/doore/crop/response/CropReferenceResponse.java
  src/main/java/doore/study/api/StudyController.java
  src/main/java/doore/study/application/StudyQueryService.java
  src/main/java/doore/study/application/dto/response/StudyResponse.java
  src/main/java/doore/study/application/dto/response/personalStudyResponse/PersonalStudyDetailResponse.java
  src/main/java/doore/study/application/dto/response/totalStudyResponse/CurriculumItemReferenceResponse.java
  src/main/java/doore/study/application/dto/response/totalStudyResponse/CurriculumItemResponse.java
  src/main/java/doore/study/application/dto/response/totalStudyResponse/ParticipantCurriculumItemResponse.java
  src/main/java/doore/study/application/dto/response/totalStudyResponse/StudyDetailResponse.java
  src/main/java/doore/study/application/dto/response/totalStudyResponse/StudySimpleResponse.java
  src/main/java/doore/study/domain/repository/StudyRepository.java
  src/main/java/doore/study/persistence/StudyDao.java
  src/main/java/doore/study/persistence/dto/StudyInformation.java
  src/main/java/doore/study/persistence/dto/StudyOverview.java
  src/main/java/doore/team/api/TeamController.java
  src/main/java/doore/team/application/TeamQueryService.java
  src/main/java/doore/team/application/dto/response/TeamReferenceResponse.java
  src/main/java/doore/team/domain/TeamRepository.java
  src/test/java/doore/restdocs/RestDocsTest.java
  src/test/java/doore/restdocs/docs/StudyApiDocsTest.java
  src/test/java/doore/restdocs/docs/TeamApiDocsTest.java
  src/test/java/doore/study/StudyFixture.java
  src/test/java/doore/study/api/StudyControllerTest.java
  src/test/java/doore/study/application/StudyQueryServiceTest.java
  src/test/java/doore/team/api/TeamControllerTest.java
  src/test/java/doore/team/application/TeamQueryServiceTest.java
  src/test/java/doore/team/domain/TeamRepositoryTest.java
Labels: 🌱 기능 구현

#105 Feature/#77 권한 관련 기능 구현
  src/docs/asciidoc/member.adoc
  src/main/java/doore/attendance/api/AttendanceController.java
  src/main/java/doore/attendance/application/AttendanceCommandService.java
  src/main/java/doore/login/exception/LoginExceptionType.java
  src/main/java/doore/login/utils/AuthorizationExtractor.java
  src/main/java/doore/member/api/MemberController.java
  src/main/java/doore/member/application/MemberCommandService.java
  src/main/java/doore/member/domain/MemberDetails.java
  src/main/java/doore/member/domain/StudyRole.java
  src/main/java/doore/member/domain/StudyRoleType.java
  src/main/java/doore/member/domain/TeamRole.java
  src/main/java/doore/member/domain/TeamRoleType.java
  src/main/java/doore/member/domain/repository/StudyRoleRepository.java
  src/main/java/doore/member/domain/repository/TeamRoleRepository.java
  src/main/java/doore/member/exception/MemberExceptionType.java
  src/main/java/doore/resolver/LoginMember.java
  src/main/java/doore/resolver/MemberArgumentResolver.java
  src/main/resources/schema.sql
  src/test/java/doore/attendance/application/AttendanceCommandServiceTest.java
  src/test/java/doore/document/application/DocumentCommandServiceTest.java
  src/test/java/doore/member/MemberFixture.java
  src/test/java/doore/member/application/MemberCommandServiceTest.java
  src/test/java/doore/member/domain/StudyRoleRepositoryTest.java
  src/test/java/doore/member/domain/TeamRoleRepositoryTest.java
  src/test/java/doore/restdocs/RestDocsTest.java
  src/test/java/doore/restdocs/docs/MemberApiDocsTest.java
  src/test/resources/clean.sql
Labels: 🌱 기능 구현

#114 Feature/#111 커리큘럼 관련 프론트 요청사항 수정
  src/docs/asciidoc/curriculumItem.adoc
  src/main/java/doore/study/application/CurriculumItemCommandService.java
  src/main/java/doore/study/application/dto/request/CurriculumItemManageDetailRequest.java
  src/main/java/doore/study/application/dto/request/CurriculumItemManageRequest.java
  src/main/java/doore/study/domain/CurriculumItem.java
  src/main/java/doore/study/exception/CurriculumItemExceptionType.java
  src/test/java/doore/restdocs/docs/CurriculumItemApiDocsTest.java
  src/test/java/doore/study/application/CurriculumItemCommandServiceTest.java
Labels: 🛠️ 리팩터링

#112 Refactor/애플리케이션 컨텍스트 통일
  src/main/java/doore/garden/api/GardenController.java
  src/main/java/doore/login/utils/JwtTokenGenerator.java
  src/main/resources/application.yml
  src/test/java/doore/restdocs/RestDocsTest.java
  src/test/java/doore/restdocs/docs/AttendanceApiDocsTest.java
  src/test/java/doore/restdocs/docs/CurriculumItemApiDocsTest.java
  src/test/java/doore/restdocs/docs/DocumentDocsTest.java
  src/test/java/doore/restdocs/docs/LoginApiDocsTest.java
  src/test/java/doore/restdocs/docs/MemberTeamApiDocsTest.java
  src/test/java/doore/restdocs/docs/ParticipantApiDocsTest.java
  src/test/java/doore/restdocs/docs/StudyApiDocsTest.java
  src/test/java/doore/restdocs/docs/TeamApiDocsTest.java
Labels: 🛠️ 리팩터링

#118 feat: 스터디 생성시 커리큘럼을 함께 생성하는 기능을 제거한다.
  src/main/java/doore/study/application/StudyCommandService.java
  src/main/java/doore/study/application/dto/request/StudyCreateRequest.java
  src/test/java/doore/restdocs/docs/StudyApiDocsTest.java
  src/test/java/doore/study/api/StudyControllerTest.java
  src/test/java/doore/study/application/StudyCommandServiceTest.java
Labels: 🌱 기능 구현

#129 Feature/#128 학습자료 목록 조회 rest docs api 수정
  src/test/java/doore/restdocs/docs/DocumentDocsTest.java
Labels: 🌱 기능 구현

#123 Feature/#110 권한 설정이 필요한 모든 코드를 수정한다
  src/main/java/doore/config/WebMvcConfig.java
  src/main/java/doore/document/api/DocumentController.java
  src/main/java/doore/document/application/DocumentCommandService.java
  src/main/java/doore/document/application/DocumentQueryService.java
  src/main/java/doore/document/domain/Document.java
  src/main/java/doore/member/api/MemberController.java
  src/main/java/doore/member/exception/MemberExceptionType.java
  src/main/java/doore/resolver/MemberArgumentResolver.java
  src/main/java/doore/study/api/CurriculumItemController.java
  src/main/java/doore/study/api/ParticipantController.java
  src/main/java/doore/study/api/StudyController.java
  src/main/java/doore/study/application/CurriculumItemCommandService.java
  src/main/java/doore/study/application/ParticipantCommandService.java
  src/main/java/doore/study/application/ParticipantQueryService.java
  src/main/java/doore/study/application/StudyCommandService.java
  src/main/java/doore/study/application/StudyQueryService.java
  src/main/java/doore/team/api/TeamController.java
  src/main/java/doore/team/application/TeamCommandService.java
  src/main/java/doore/team/application/TeamQueryService.java
  src/test/java/doore/attendance/application/AttendanceCommandServiceTest.java
  src/test/java/doore/attendance/domain/AttendanceRepositoryTest.java
  src/test/java/doore/document/application/DocumentCommandServiceTest.java
  src/test/java/doore/document/application/DocumentQueryServiceTest.java
  src/test/java/doore/document/domain/DocumentTest.java
  src/test/java/doore/helper/ApiTestHelper.java
  src/test/java/doore/helper/IntegrationTest.java
  src/test/java/doore/login/utils/TokenGeneratorTest.java
  src/test/java/doore/member/MemberFixture.java
  src/test/java/doore/member/application/MemberTeamQueryServiceTest.java
  src/test/java/doore/restdocs/RestDocsTest.java
  src/test/java/doore/restdocs/docs/AttendanceApiDocsTest.java
  src/test/java/doore/restdocs/docs/CurriculumItemApiDocsTest.java
  src/test/java/doore/restdocs/docs/DocumentDocsTest.java
  src/test/java/doore/restdocs/docs/LoginApiDocsTest.java
  src/test/java/doore/restdocs/docs/MemberApiDocsTest.java
  src/test/java/doore/restdocs/docs/MemberTeamApiDocsTest.java
  src/test/java/doore/restdocs/docs/ParticipantApiDocsTest.java
  src/test/java/doore/restdocs/docs/StudyApiDocsTest.java
  src/test/java/doore/restdocs/docs/TeamApiDocsTest.java
  src/test/java/doore/study/api/StudyControllerTest.java
  src/test/java/doore/study/application/CurriculumItemCommandServiceTest.java
  src/test/java/doore/study/application/ParticipantCommandServiceTest.java
  src/test/java/doore/study/application/ParticipantQueryTest.java
  src/test/java/doore/study/application/StudyCommandServiceTest.java
  src/test/java/doore/study/application/StudyQueryServiceTest.java
  src/test/java/doore/team/TeamFixture.java
  src/test/java/doore/team/api/TeamControllerTest.java
  src/test/java/doore/team/application/TeamCommandServiceTest.java
  src/test/java/doore/team/application/TeamQueryServiceTest.java
Labels: 🌱 기능 구현, 🛠️ 리팩터링
