Repository BDD-CLUB/01-doo-re-back, pull requests merged in 2024-07, with the labels that each got.

#184 Fix/#183 Participant와 MemberTeam으로 인한 오류를 해결하고 권한 검증 코드를 수정한다.
  src/main/java/doore/document/application/DocumentQueryService.java
  src/main/java/doore/member/application/MemberTeamQueryService.java
  src/main/java/doore/member/domain/repository/MemberTeamRepository.java
  src/main/java/doore/study/api/CurriculumItemController.java
  src/main/java/doore/study/application/CurriculumItemCommandService.java
  src/main/java/doore/study/application/ParticipantCommandService.java
  src/main/java/doore/study/application/ParticipantQueryService.java
  src/main/java/doore/study/application/StudyCommandService.java
  src/main/java/doore/study/domain/repository/StudyRepository.java
  src/main/java/doore/team/application/TeamCommandService.java
  src/test/java/doore/study/application/CurriculumItemCommandServiceTest.java
  src/test/java/doore/study/application/ParticipantCommandServiceTest.java
  src/test/java/doore/study/application/StudyCommandServiceTest.java
  src/test/java/doore/team/application/TeamCommandServiceTest.java
Labels: 🐛 버그

#175 Feature/#172 팀원 삭제 api를 개발한다
  src/docs/asciidoc/memberTeam.adoc
  src/main/java/doore/member/api/MemberTeamController.java
  src/main/java/doore/member/application/MemberTeamCommandService.java
  src/main/java/doore/member/domain/repository/MemberTeamRepository.java
  src/test/java/doore/member/application/MemberTeamCommandServiceTest.java
  src/test/java/doore/restdocs/RestDocsTest.java
  src/test/java/doore/restdocs/docs/MemberTeamApiDocsTest.java
Labels: 🌱 기능 구현

#186 Feature/#154 study관련 테스트 빌드 실패 해결
  src/test/java/doore/study/application/StudyQueryServiceTest.java
  src/test/java/doore/study/domain/ParticipantCurriculumItemRepositoryTest.java
Labels: 🐛 버그

#188 fix: 첫번째 행은 정렬에서 제외되던 부분 수정
  src/main/java/doore/study/application/CurriculumItemCommandService.java
Labels: 🐛 버그

#190 Feature/#174 학습자료 조회 시 uploader 정보 조회 추가
  src/main/java/doore/document/application/DocumentQueryService.java
  src/main/java/doore/document/application/dto/response/DocumentCondensedResponse.java
  src/main/java/doore/document/application/dto/response/DocumentDetailResponse.java
  src/test/java/doore/document/application/DocumentQueryServiceTest.java
  src/test/java/doore/restdocs/docs/DocumentDocsTest.java
Labels: 🌱 기능 구현

#191 Feature/#177 crop table을 삭제한다
  src/main/java/doore/crop/domain/Crop.java
  src/main/java/doore/crop/domain/repository/CropRepository.java
  src/main/java/doore/crop/exception/CropException.java
  src/main/java/doore/crop/exception/CropExceptionType.java
  src/main/java/doore/crop/response/CropReferenceResponse.java
  src/main/java/doore/study/application/StudyQueryService.java
  src/main/java/doore/study/application/dto/response/StudyResponse.java
  src/main/resources/schema.sql
  src/test/java/doore/crop/CropFixture.java
  src/test/java/doore/restdocs/docs/StudyApiDocsTest.java
  src/test/java/doore/study/StudyFixture.java
  src/test/java/doore/study/application/StudyQueryServiceTest.java
Labels: 🌱 기능 구현

#196 fix: findTeamRoleByMemberId을 findTeamRoleByTeamIdAndMemberId로 수정한다.
  src/main/java/doore/member/application/MemberTeamQueryService.java
Labels: 🐛 버그

#197 Fix/#195 파라미터 오류를 해결한다.
  src/main/java/doore/member/application/MemberTeamQueryService.java
Labels: 🐛 버그

#199 Feature/#198 학습자료 목록 조회 시 응답을 수정한다
  src/main/java/doore/document/api/DocumentController.java
  src/main/java/doore/document/application/DocumentQueryService.java
  src/main/java/doore/document/application/dto/response/DocumentCondensedResponse.java
  src/main/java/doore/document/application/dto/response/DocumentResponse.java
  src/test/java/doore/document/application/DocumentQueryServiceTest.java
  src/test/java/doore/restdocs/docs/DocumentDocsTest.java
Labels: 🌱 기능 구현, 👩‍💻 프론트 요청사항

#203 Feature/#202 학습자료 목록 조회시 total 개수를 반환한다
  src/main/java/doore/document/api/DocumentController.java
  src/main/java/doore/document/application/DocumentQueryService.java
  src/test/java/doore/document/application/DocumentQueryServiceTest.java
  src/test/java/doore/restdocs/docs/DocumentDocsTest.java
Labels: 🌱 기능 구현, 👩‍💻 프론트 요청사항

#205 fix: 팀 가입이 되지 않는 오류를 수정한다.
  src/main/java/doore/team/application/TeamCommandService.java
Labels: 🐛 버그

#208 Fix/#207 참여자 조회시 직렬화 문제를 해결한다
  src/main/java/doore/study/api/ParticipantController.java
  src/main/java/doore/study/application/ParticipantQueryService.java
  src/main/java/doore/study/application/dto/response/ParticipantResponse.java
  src/test/java/doore/restdocs/docs/ParticipantApiDocsTest.java
  src/test/java/doore/study/application/ParticipantCommandServiceTest.java
  src/test/java/doore/study/application/ParticipantQueryTest.java
Labels: 🐛 버그

#194 Feature/#192 팀 스터디 삭제 시 팀원 스터디원 함께 삭제
  src/main/java/doore/member/domain/Participant.java
  src/main/java/doore/member/domain/repository/TeamRoleRepository.java
  src/main/java/doore/study/application/StudyCommandService.java
  src/main/java/doore/team/application/TeamCommandService.java
  src/test/java/doore/study/application/ParticipantCommandServiceTest.java
Labels: 🌱 기능 구현

#210 Feature/#179 커리큘럼 파트의 메서드를 짧게 수정한다
  src/main/java/doore/member/application/MemberTeamCommandService.java
  src/main/java/doore/member/application/MemberTeamQueryService.java
  src/main/java/doore/member/application/convenience/StudyRoleValidateAccessPermission.java
  src/main/java/doore/member/application/convenience/TeamRoleValidateAccessPermission.java
  src/main/java/doore/study/application/CurriculumItemCommandService.java
  src/main/java/doore/study/application/ParticipantCommandService.java
  src/main/java/doore/study/application/ParticipantQueryService.java
  src/main/java/doore/study/application/StudyCommandService.java
  src/main/java/doore/team/application/TeamCommandService.java
  src/test/java/doore/member/application/MemberTeamCommandServiceTest.java
  src/test/java/doore/study/application/ParticipantQueryTest.java
Labels: 🛠️ 리팩터링
