Repository BDD-CLUB/01-doo-re-back, pull requests merged in 2024-03, with the labels that each got.

#96 Feature/#63 팀원 목록 조회 및 검색 구현
  src/docs/asciidoc/doore.adoc
  src/docs/asciidoc/memberTeam.adoc
  src/main/java/doore/member/api/MemberTeamController.java
  src/main/java/doore/member/application/MemberTeamQueryService.java
  src/main/java/doore/member/application/dto/response/MemberResponse.java
  src/main/java/doore/member/domain/MemberTeam.java
  src/main/java/doore/member/domain/repository/MemberTeamRepository.java
  src/test/java/doore/login/application/LoginServiceTest.java
  src/test/java/doore/member/MemberFixture.java
  src/test/java/doore/member/api/MemberTeamControllerTest.java
  src/test/java/doore/member/application/MemberCommandServiceTest.java
  src/test/java/doore/member/application/MemberTeamQueryServiceTest.java
  src/test/java/doore/member/domain/repository/MemberTeamRepositoryTest.java
  src/test/java/doore/restdocs/RestDocsTest.java
  src/test/java/doore/restdocs/docs/MemberTeamApiDocsTest.java
  src/test/java/doore/study/api/StudyControllerTest.java
  src/test/java/doore/study/application/CurriculumItemCommandServiceTest.java
  src/test/java/doore/study/application/StudyCommandServiceTest.java
  src/test/java/doore/study/application/StudyQueryServiceTest.java
Labels: 🌱 기능 구현, 😑 P2

#83 Feature/#78 출석 구현
  src/docs/asciidoc/attendance.adoc
  src/main/java/doore/attendance/api/AttendanceController.java
  src/main/java/doore/attendance/application/AttendanceCommandService.java
  src/main/java/doore/attendance/domain/Attendance.java
  src/main/java/doore/attendance/domain/repository/AttendanceRepository.java
  src/main/java/doore/attendance/exception/AttendanceException.java
  src/main/java/doore/attendance/exception/AttendanceExceptionType.java
  src/main/resources/schema.sql
  src/test/java/doore/attendance/application/AttendanceCommandServiceTest.java
  src/test/java/doore/attendance/domain/AttendanceRepositoryTest.java
  src/test/java/doore/restdocs/RestDocsTest.java
  src/test/java/doore/restdocs/docs/AttendanceApiDocsTest.java
  src/test/java/doore/restdocs/docs/StudyApiDocsTest.java
Labels: 🌱 기능 구현

#90 Refactor/#89 스터디 조회 기능 수정
  src/docs/asciidoc/participant.adoc
  src/docs/asciidoc/study.adoc
  src/main/java/doore/crop/domain/Crop.java
  src/main/java/doore/crop/domain/repository/CropRepository.java
  src/main/java/doore/crop/exception/CropException.java
  src/main/java/doore/crop/exception/CropExceptionType.java
  src/main/java/doore/crop/response/CropReferenceResponse.java
  src/main/java/doore/study/api/ParticipantController.java
  src/main/java/doore/study/api/StudyController.java
  src/main/java/doore/study/application/ParticipantCommandService.java
  src/main/java/doore/study/application/ParticipantQueryService.java
  src/main/java/doore/study/application/StudyCommandService.java
  src/main/java/doore/study/application/StudyQueryService.java
  src/main/java/doore/study/application/dto/response/CurriculumItemResponse.java
  src/main/java/doore/study/application/dto/response/StudyDetailResponse.java
  src/main/java/doore/study/application/dto/response/StudyResponse.java
  src/main/java/doore/study/application/dto/response/personalStudyResponse/PersonalCurriculumItemResponse.java
  src/main/java/doore/study/application/dto/response/personalStudyResponse/PersonalStudyDetailResponse.java
  src/main/java/doore/study/application/dto/response/totalStudyResponse/CurriculumItemResponse.java
  src/main/java/doore/study/application/dto/response/totalStudyResponse/ParticipantCurriculumItemResponse.java
  src/main/java/doore/study/application/dto/response/totalStudyResponse/StudyDetailResponse.java
  src/main/java/doore/team/application/dto/response/TeamReferenceResponse.java
  src/test/java/doore/crop/CropFixture.java
  src/test/java/doore/restdocs/RestDocsTest.java
  src/test/java/doore/restdocs/docs/ParticipantApiDocsTest.java
  src/test/java/doore/restdocs/docs/StudyApiDocsTest.java
  src/test/java/doore/study/StudyFixture.java
  src/test/java/doore/study/api/StudyControllerTest.java
  src/test/java/doore/study/application/ParticipantCommandServiceTest.java
  src/test/java/doore/study/application/ParticipantQueryTest.java
  src/test/java/doore/study/application/StudyCommandServiceTest.java
  src/test/java/doore/study/application/StudyQueryServiceTest.java
  src/test/java/doore/study/application/StudyServiceTest.java
Labels: 🌱 기능 구현, 🛠️ 리팩터링

#104 Bug/#103 팀원 목록 조회 테스트가 실패하는 문제
  src/main/java/doore/member/application/MemberTeamQueryService.java
Labels: 🐛 버그, 🤨 P1
