Repository BDD-CLUB/01-doo-re-back, pull requests merged in 2024-01, with the labels that each got.

#17 Feature/#7-CICD_파이프라인_구축-1
  .github/workflows/deploy_dev.yml
Labels: 🐳 인프라

#18 Feature/#11-RestDocs를_셋팅한다
  build.gradle
  src/docs/asciidoc/index.adoc
  src/test/java/doore/restdocs/AbstractRestDocsTests.java
  src/test/java/doore/restdocs/RestDocsConfiguration.java
Labels: 📄 문서 작업

#23 Feature/#7-CI/CD_파이프라인을_구축한다
  .github/workflows/deploy_dev.yml
Labels: 🐛 버그, 🐳 인프라, 🤨 P1

#29 Feature/#28-개발 서버에 Rest Docs가 배포가 안되는 문제 해결
  .github/workflows/deploy_dev.yml
  build.gradle
Labels: 🐛 버그, 🐳 인프라, 😑 P2

#32 Feature/#13 팀 CUD 구현 & 테스트 구조 확립
  src/docs/asciidoc/doore.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/team.adoc
  src/main/java/doore/base/BaseEntity.java
  src/main/java/doore/exception/ExceptionAdvice.java
  src/main/java/doore/exception/ExceptionResponse.java
  src/main/java/doore/team/api/TeamController.java
  src/main/java/doore/team/application/TeamCommandService.java
  src/main/java/doore/team/application/dto/request/TeamCreateRequest.java
  src/main/java/doore/team/application/dto/request/TeamUpdateRequest.java
  src/main/java/doore/team/domain/Team.java
  src/main/java/doore/team/domain/TeamRepository.java
  src/main/java/doore/team/exception/TeamException.java
  src/main/java/doore/team/exception/TeamExceptionType.java
  src/test/java/doore/DooreApplicationTests.java
  src/test/java/doore/helper/IntegrationTest.java
  src/test/java/doore/helper/RepositorySliceTest.java
  src/test/java/doore/restdocs/RestDocsTest.java
  src/test/java/doore/restdocs/docs/TeamApiDocsTest.java
  src/test/java/doore/team/TeamFixture.java
  src/test/java/doore/team/api/TeamControllerTest.java
  src/test/java/doore/team/application/TeamCommandServiceTest.java
  src/test/java/doore/team/domain/TeamRepositoryTest.java
  src/test/java/doore/team/domain/TeamTest.java
Labels: 🌱 기능 구현, 🤨 P1

#26 Feature/#19-CORS 설정
  src/main/java/doore/config/CorsConfig.java
  src/main/resources/application.yml
Labels: 🌱 기능 구현

#43 Feature/#41-Gradle 캐싱 적용
  .github/workflows/deploy_dev.yml
Labels: 🌱 기능 구현, 🐳 인프라

#50 Feature/#10 회원가입 로그인 기능 구현
  build.gradle
  src/docs/asciidoc/doore.adoc
  src/docs/asciidoc/login.adoc
  src/main/java/doore/DooreApplication.java
  src/main/java/doore/config/RestTemplateConfig.java
  src/main/java/doore/login/api/LoginController.java
  src/main/java/doore/login/application/LoginService.java
  src/main/java/doore/login/application/dto/request/GoogleAccessTokenRequest.java
  src/main/java/doore/login/application/dto/request/GoogleLoginRequest.java
  src/main/java/doore/login/application/dto/response/GoogleAccessTokenResponse.java
  src/main/java/doore/login/application/dto/response/GoogleAccountProfileResponse.java
  src/main/java/doore/login/application/dto/response/LoginResponse.java
  src/main/java/doore/login/exception/LoginException.java
  src/main/java/doore/login/exception/LoginExceptionType.java
  src/main/java/doore/login/utils/GoogleClient.java
  src/main/java/doore/login/utils/JwtTokenGenerator.java
  src/main/java/doore/member/application/MemberCommandService.java
  src/main/java/doore/member/domain/Member.java
  src/main/java/doore/member/domain/repository/MemberRepository.java
  src/main/resources/application.yml
  src/test/java/doore/helper/IntegrationTest.java
  src/test/java/doore/login/application/LoginServiceTest.java
  src/test/java/doore/login/utils/TokenGeneratorTest.java
  src/test/java/doore/member/MemberFixture.java
  src/test/java/doore/member/application/MemberCommandServiceTest.java
  src/test/java/doore/restdocs/RestDocsTest.java
  src/test/java/doore/restdocs/docs/LoginApiDocsTest.java
  src/test/resources/clean.sql
Labels: 🌱 기능 구현, 😑 P2

#52 Feature/#14 스터디 crud 기능 구현
  src/docs/asciidoc/study.adoc
  src/main/java/doore/study/api/StudyController.java
  src/main/java/doore/study/application/StudyCommandService.java
  src/main/java/doore/study/application/StudyQueryService.java
  src/main/java/doore/study/application/dto/request/CurriculumItemsRequest.java
  src/main/java/doore/study/application/dto/request/StudyCreateRequest.java
  src/main/java/doore/study/application/dto/request/StudyUpdateRequest.java
  src/main/java/doore/study/application/dto/response/CurriculumItemResponse.java
  src/main/java/doore/study/application/dto/response/StudyDetailResponse.java
  src/main/java/doore/study/domain/CurriculumItem.java
  src/main/java/doore/study/domain/Study.java
  src/main/java/doore/study/domain/repository/CurriculumItemRepository.java
  src/main/java/doore/study/domain/repository/StudyRepository.java
  src/main/java/doore/study/exception/StudyException.java
  src/main/java/doore/study/exception/StudyExceptionType.java
  src/test/java/doore/helper/IntegrationTest.java
  src/test/java/doore/restdocs/RestDocsTest.java
  src/test/java/doore/restdocs/docs/StudyApiDocsTest.java
  src/test/java/doore/study/StudyFixture.java
  src/test/java/doore/study/api/StudyControllerTest.java
  src/test/java/doore/study/application/StudyServiceTest.java
  src/test/java/doore/study/domain/StudyTest.java
Labels: 🌱 기능 구현
