Repository BDD-CLUB/01-doo-re-back, pull requests merged in 2024-08, with the labels that each got.

#217 Feature/#215 초대 링크 발급은 팀장만 가능하도록 한다
  src/main/java/doore/team/api/TeamController.java
  src/main/java/doore/team/application/TeamCommandService.java
  src/test/java/doore/restdocs/docs/TeamApiDocsTest.java
  src/test/java/doore/team/application/TeamCommandServiceTest.java
Labels: 🌱 기능 구현

#220 Fix/#219 커리큘럼 생성 및 수정 문제를 해결한다
  src/main/java/doore/garden/application/convenience/GardenConvenience.java
  src/main/java/doore/study/application/CurriculumItemCommandService.java
  src/main/java/doore/study/application/convenience/StudyAuthorization.java
  src/main/java/doore/study/application/convenience/StudyConvenience.java
  src/main/java/doore/study/application/dto/request/CurriculumItemManageDetailRequest.java
  src/main/java/doore/study/domain/CurriculumItem.java
  src/main/java/doore/study/domain/repository/CurriculumItemRepository.java
  src/main/java/doore/study/domain/repository/ParticipantCurriculumItemRepository.java
  src/test/java/doore/restdocs/docs/CurriculumItemApiDocsTest.java
  src/test/java/doore/study/application/CurriculumItemQueryServiceTest.java
Labels: 🐛 버그, 🛠️ 리팩터링

#221 Feature/#214 학습자료에 학습자료 이름이 뜨도록 수정한다
  src/main/java/doore/document/application/DocumentCommandService.java
  src/main/java/doore/document/application/DocumentQueryService.java
  src/main/java/doore/document/application/dto/response/FileResponse.java
  src/main/java/doore/document/domain/Document.java
  src/main/java/doore/document/domain/File.java
  src/main/java/doore/garden/application/convenience/GardenConvenience.java
  src/main/java/doore/member/application/convenience/MemberAuthorization.java
  src/main/java/doore/member/application/convenience/MemberConvenience.java
  src/main/java/doore/study/application/convenience/StudyConvenience.java
  src/main/java/doore/team/application/convenience/TeamAuthorization.java
  src/main/resources/schema.sql
  src/test/java/doore/document/application/DocumentCommandServiceTest.java
  src/test/java/doore/restdocs/docs/DocumentDocsTest.java
  src/test/java/doore/study/application/CurriculumItemCommandServiceTest.java
Labels: 🌱 기능 구현, 🛠️ 리팩터링

#224 Feature/#222 스터디 랭킹 반환시 페이지네이션으로 반환한다
  src/main/java/doore/member/application/convenience/StudyRoleConvenience.java
  src/main/java/doore/member/domain/MemberTeam.java
  src/main/java/doore/study/api/StudyController.java
  src/main/java/doore/study/application/StudyCommandService.java
  src/main/java/doore/study/application/StudyQueryService.java
  src/main/java/doore/team/application/convenience/TeamAuthorization.java
  src/test/java/doore/restdocs/docs/StudyApiDocsTest.java
  src/test/java/doore/study/api/StudyControllerTest.java
  src/test/java/doore/study/application/StudyCommandServiceTest.java
Labels: 🐛 버그, 🌱 기능 구현, 🛠️ 리팩터링
