Repository BDD-CLUB/01-doo-re-back, pull requests merged in 2024-02, with the labels that each got.

#58 Feature/#46_CICD_DB_Docker_고도화
  .github/workflows/deploy_dev.yml
  build.gradle
Labels: 🐳 인프라, 😑 P2, 👍 개선

#53 Feature/#30 커리큘럼 curd 구현
  src/docs/asciidoc/curriculumItem.adoc
  src/main/java/doore/member/domain/Participant.java
  src/main/java/doore/member/domain/repository/ParticipantRepository.java
  src/main/java/doore/study/api/CurriculumItemController.java
  src/main/java/doore/study/api/StudyController.java
  src/main/java/doore/study/application/CurriculumItemCommandService.java
  src/main/java/doore/study/application/StudyCommandService.java
  src/main/java/doore/study/application/StudyQueryService.java
  src/main/java/doore/study/application/dto/request/CurriculumItemRequest.java
  src/main/java/doore/study/application/dto/request/CurriculumItemsRequest.java
  src/main/java/doore/study/application/dto/request/StudyCreateRequest.java
  src/main/java/doore/study/domain/CurriculumItem.java
  src/main/java/doore/study/domain/ParticipantCurriculumItem.java
  src/main/java/doore/study/domain/Study.java
  src/main/java/doore/study/domain/repository/CurriculumItemRepository.java
  src/main/java/doore/study/domain/repository/ParticipantCurriculumItemRepository.java
  src/main/java/doore/study/exception/CurriculumItemException.java
  src/main/java/doore/study/exception/CurriculumItemExceptionType.java
  src/test/java/doore/restdocs/docs/CurriculumItemApiDocsTest.java
  src/test/java/doore/restdocs/docs/StudyApiDocsTest.java
  src/test/java/doore/study/CurriculumItemFixture.java
  src/test/java/doore/study/StudyFixture.java
  src/test/java/doore/study/api/CurriculumItemControllerTest.java
  src/test/java/doore/study/application/CurriculumItemCommandServiceTest.java
  src/test/java/doore/study/application/StudyServiceTest.java
  src/test/java/doore/study/domain/CurriculumItemTest.java
  src/test/java/doore/study/domain/StudyTest.java
Labels: 🌱 기능 구현

#80 Feature/#74 배포 서버 cicd 스크립트 작성
  .github/workflows/deploy_prod.yml
Labels: 🐳 인프라, 🐈 깃허브

#71 Feature/#45 s3 이미지 저장 기능 구현
  build.gradle
  src/docs/asciidoc/team.adoc
  src/main/java/doore/base/BaseEntity.java
  src/main/java/doore/config/JpaAuditingConfig.java
  src/main/java/doore/config/S3Config.java
  src/main/java/doore/file/application/S3DocumentFileService.java
  src/main/java/doore/file/application/S3FileService.java
  src/main/java/doore/file/application/S3ImageFileService.java
  src/main/java/doore/file/exception/FileException.java
  src/main/java/doore/file/exception/FileExceptionType.java
  src/main/java/doore/team/api/TeamController.java
  src/main/java/doore/team/application/TeamCommandService.java
  src/main/java/doore/team/domain/Team.java
  src/main/resources/application.yml
  src/test/java/doore/helper/ApiTestHelper.java
  src/test/java/doore/helper/IntegrationTest.java
  src/test/java/doore/restdocs/RestDocsTest.java
  src/test/java/doore/restdocs/docs/TeamApiDocsTest.java
  src/test/java/doore/team/api/TeamControllerTest.java
  src/test/java/doore/team/application/TeamCommandServiceTest.java
  src/test/java/doore/team/domain/TeamRepositoryTest.java
  src/test/java/doore/team/domain/TeamTest.java
  src/test/resources/images/testImage.png
Labels: 🌱 기능 구현

#85 Feature/#12 팀원 초대 링크 생성
  build.gradle
  src/docs/asciidoc/team.adoc
  src/main/java/doore/config/RedisConfig.java
  src/main/java/doore/team/api/TeamController.java
  src/main/java/doore/team/application/TeamCommandService.java
  src/main/java/doore/team/application/dto/request/TeamInviteCodeRequest.java
  src/main/java/doore/team/application/dto/response/TeamInviteCodeResponse.java
  src/main/java/doore/team/exception/TeamExceptionType.java
  src/main/java/doore/util/RandomUtil.java
  src/main/java/doore/util/RedisUtil.java
  src/main/resources/application.yml
  src/test/java/doore/helper/IntegrationTest.java
  src/test/java/doore/restdocs/docs/TeamApiDocsTest.java
  src/test/java/doore/team/application/TeamCommandServiceTest.java
Labels: 🌱 기능 구현
